Loader:
  data_dir: 'data'

Preprocessor:
  save_dir: 'prep'

Matcher:
  split_year: 2022
  split_month: 6
  split_day: 1

EDA:
  scatter:
    point_size: 5
    x_title: 'data_x'
    y_titlle: 'data_y'
  bar:
    point_size: 5
    x_title: 'data_x'
    y_titlle: 'data_y'

Model:
  